// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/Mekawy5/chatserv/pkg/application"
	"github.com/Mekawy5/chatserv/pkg/chat"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitApplicationApi(db *gorm.DB) *application.ApplicationApi {
	applicationRepository := application.NewApplicationRepository(db)
	applicationService := application.NewApplicationService(applicationRepository)
	applicationApi := application.NewApplicationApi(applicationService)
	return applicationApi
}

func InitChatApi(db *gorm.DB) *chat.ChatApi {
	chatRepository := chat.NewChatRepository(db)
	chatService := chat.NewChatService(chatRepository)
	chatApi := chat.NewChatApi(chatService)
	return chatApi
}
