// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/Mekawy5/chatserv/pkg/controllers"
	"github.com/Mekawy5/chatserv/tools"
)

// Injectors from wire.go:

func InitApplicationController(rmc *tools.RabbitClient) *controllers.ApplicationController {
	applicationController := controllers.NewApplicationController(rmc)
	return applicationController
}

func InitMessageController(rmc *tools.RabbitClient) *controllers.MessageController {
	messageController := controllers.NewMessageController(rmc)
	return messageController
}

func InitChatController(rabbitClient *tools.RabbitClient) *controllers.ChatConroller {
	chatConroller := controllers.NewChatConroller(rabbitClient)
	return chatConroller
}
