version: '3'
services:
  # go application
  app:
    container_name: "chat_app"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:8080"
    user: "root"
    volumes: 
      - ./:/go/src/github.com/Mekawy5/chatserv
    env_file: .env
    restart: on-failure
    entrypoint: sh -c './wait-for.sh database:3306 -t 60 -- CompileDaemon --build="go build -installsuffix 'static' -o /app ./cmd" --command=/app'

  # mysql db
  database:
    container_name: "chat_app_database"
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"


  # redis cache db
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

volumes:
  db_data:
  redis-data:

networks: 
  default:
    external: 
      name: queue-service_default