version: '3'
services:
  # go application
  app:
    container_name: "chat_app"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on: 
      - database
    restart: on-failure

  # mysql db
  database:
    container_name: "chat_app_database"
    image: mysql:5.7
    volumes:
        - db_data:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=chat
        - MYSQL_ROOT_PASSWORD=123
    ports:
        - "3306:3306"



volumes:
  db_data:
