version: '3'
services:

  # mysql db
  database:
    container_name: "chat_app_database"
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"

  # rabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "chat_app_rabbitmq"
    hostname: chatrmq
    volumes:
      - ./deploy/rabbitmq/rabbitmq.config/:/etc/rabbitmq/rabbitmq.config
      - ./deploy/rabbitmq/definitions.json/:/etc/rabbitmq/definitions.json
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"


  # redis cache db
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  # go application
  app:
    container_name: "chat_app"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    restart: on-failure
    depends_on: 
      - database
      - rabbitmq

volumes:
  db_data:
  rabbitmq_data:
  redis-data:
